### ISSUE TITLE
Warning: SHA1 support is deprecated

### ISSUE THREAD

**Issue by MyRealityCoding** [bripkens/dock#34]
When freshly install *dock* from the **bripkens/dock** repository, the following warning is shown:
```bash
Warning: SHA1 support is deprecated and will be removed in a future version.
Please switch this formula to SHA256.
```

**Comment by bripkens** [comment]
Thanks for the hint! Upgraded to SHA256 in https://github.com/bripkens/homebrew-dock/commit/e29f0bd2063e4bd65dae1526cadd11a78d8c5be0
